- src/auth/auth.service.ts
- src/auth/strategies/jwt.strategy.ts
> Feature auth 768625

- src/auth/auth.service.ts
- src/i18n/en/common.json
- src/i18n/en/confirm-email.json
- src/i18n/en/reset-password.json
- src/i18n/vi/common.json
- src/i18n/vi/confirm-email.json
- src/i18n/vi/confirm-new-email.json
- src/i18n/vi/reset-password.json
- src/mail/mail-templates/activation.hbs
- src/mail/mail-templates/reset-password.hbs
- src/mail/mail.service.ts
[BE] Email Template
https://c5qcgij075a.sg.larksuite.com/record/QOHsrkqE8e1KyMcu8dDlKcRHgbg
> [BE] Email Template

- src/mail/mail-templates/activation.hbs
- src/mail/mail-templates/reset-password.hbs
[BE] Email Template
https://c5qcgij075a.sg.larksuite.com/record/QOHsrkqE8e1KyMcu8dDlKcRHgbg
> fix(Mailer): fixed email templates

- src/users/dto/query-user.dto.ts
- src/users/infrastructure/persistence/relational/repositories/user.repository.ts
> chore: add filter topics of interest

- package-lock.json
- package.json
- src/app.module.ts
- src/casl/ability.factory.ts
- src/casl/casl.module.ts
- src/casl/decorators/casl.decorator.ts
- src/casl/guards/casl.guard.ts
- src/users/users.controller.ts
- src/users/users.module.ts
- tsconfig.json
> feat: define casl module

- prisma/migrations/20250310095641_init_time_slots/migration.sql
- prisma/schema.prisma
- src/app.module.ts
- src/database/seeds/relational/run-seed.ts
- src/database/seeds/relational/seed.module.ts
- src/database/seeds/relational/time-slot/time-slot-seed.module.ts
- src/database/seeds/relational/time-slot/time-slot-seed.service.ts
- src/time-slots/domain/time-slot.ts
- src/time-slots/dto/create-time-slot.dto.ts
- src/time-slots/infrastructure/persistence/relational/entities/tims-slot.entity.ts
- src/time-slots/infrastructure/persistence/relational/mappers/time-slot.mapper.ts
- src/time-slots/infrastructure/persistence/relational/relational-persistence.module.ts
- src/time-slots/infrastructure/persistence/relational/repositories/time-slot.repository.ts
- src/time-slots/infrastructure/persistence/time-slot.repository.ts
- src/time-slots/time-slots.controller.ts
- src/time-slots/time-slots.module.ts
- src/time-slots/time-slots.service.ts
test in local
- seed data:
- api:
> feat: [367985] time slot

- src/reading-sessions/infrastructure/persistence/relational/repositories/reading-sessions.repository.ts
**## WHAT**
[BE] Create reading session API 
**## WHY**
https://c5qcgij075a.sg.larksuite.com/record/JJlErGOetez8Dmcaa3mlT4m4gBh
**## NOTES**
> [177644] fixed getting reading session list API

- src/auth-google/auth-google.module.ts
- src/auth-google/auth-google.service.ts
- src/config/app.config.ts
- src/mailer/mailer.service.ts
- src/topics/dto/create-topics.dto.ts
- src/topics/topics.controller.ts
In this PR,
We will update CRD APIs for topics domain, also update google authen for local env
> feat: update CRD topics

- src/hubers/dto/find-all-hubers.dto.ts
- src/hubers/hubers.controller.ts
- src/hubers/hubers.module.ts
- src/hubers/hubers.service.ts
- src/hubers/infrastructure/persistence/huber.repository.ts
- src/hubers/infrastructure/persistence/relational/entities/huber.entity.ts
- src/hubers/infrastructure/persistence/relational/repositories/huber.repository.ts
- src/users/dto/query-user.dto.ts
**## WHAT**
[BE] List hubers API not allow topic list
**## WHY**
https://c5qcgij075a.sg.larksuite.com/record/RSjMrNsv2ehY1CcW8Sjlk7Iig8f
**## NOTES**
'http://localhost:3001/api/v1/hubers' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6eyJpZCI6MywibmFtZSI6IlJlYWRlciIsIl9fZW50aXR5IjoiUm9sZUVudGl0eSJ9LCJzZXNzaW9uSWQiOjksImlhdCI6MTc0NTA2NTgwOSwiZXhwIjoxNzQ1MTUyMjA5fQ.w8JunRSL3B9JEZ8c3KnwoWknVLqbW5Dt6FbLbePhxi0'
'http://localhost:3001/api/v1/hubers?topicIds=1&topicIds=2&topicIds=3' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6eyJpZCI6MywibmFtZSI6IlJlYWRlciIsIl9fZW50aXR5IjoiUm9sZUVudGl0eSJ9LCJzZXNzaW9uSWQiOjksImlhdCI6MTc0NTA …
> [743341] modified query hubers aggregate

- src/hubers/hubers.service.ts
**## WHAT**
[BE] List hubers API not allow topic list
**## WHY**
https://c5qcgij075a.sg.larksuite.com/record/RSjMrNsv2ehY1CcW8Sjlk7Iig8f
**## NOTES**
> [743341] fixed count queried items

- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/auth/dto/register-to-humanbook.ts
- src/time-slots/time-slots.controller.ts
- src/time-slots/time-slots.service.ts
api /register/human-books: 
- verify topic ids
- add role human book
- fix swagger example data
api /time-slots
- return timeslots by jwt
- use by huber
api /time-slots/:id
- return timeslots by id
- use by user
> Hotfix timeslots

- src/reading-sessions/dto/reading-session/find-all-reading-sessions-query.dto.ts
- src/reading-sessions/infrastructure/persistence/relational/repositories/reading-sessions.repository.ts
> chore: filter upcoming events

- src/hubers/hubers.controller.ts
- src/hubers/hubers.service.ts
> chore: hide password list hubers

- src/stories/dto/find-all-stories.dto.ts
- src/stories/infrastructure/persistence/relational/repositories/story.repository.ts
- src/stories/stories.controller.ts
> chore: filter stories by publish status

- src/reading-sessions/dto/reading-session/update-reading-session.dto.ts
> chore: cancel reading session with note

- src/reading-sessions/infrastructure/persistence/relational/repositories/reading-sessions.repository.ts
- src/reading-sessions/reading-sessions.service.ts
> chore: verify overlap session

- src/stories/stories.controller.ts
- src/stories/stories.service.ts
> chore: re-enable delete story

- src/fav-stories/dto/save-fav-story.dto.ts
- src/fav-stories/fav-stories.controller.ts
- src/fav-stories/fav-stories.service.ts
Anh chị review giúp em với ạ. Implement favorites API
> feat: implement favourites API

- src/casl/ability.factory.ts
- src/reading-sessions/dto/reading-session/find-all-reading-sessions-query.dto.ts
- src/reading-sessions/infrastructure/persistence/relational/repositories/reading-sessions.repository.ts
- src/reading-sessions/reading-sessions.controller.ts
- src/reading-sessions/reading-sessions.service.ts
**## WHAT**
[BE] Filter owner scoped reading sessions by status 
**## WHY**
https://c5qcgij075a.sg.larksuite.com/record/BDaKrqgmMe4OSvcX3Nil9TSnghd
**## NOTES**
'http://localhost:3001/api/v1/reading-sessions?sessionStatus=approved' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6eyJpZCI6MSwibmFtZSI6IkFkbWluIiwiX19lbnRpdHkiOiJSb2xlRW50aXR5In0sInNlc3Npb25JZCI6MjQsImlhdCI6MTc0NzU5MDU3MiwiZXhwIjoxNzQ3Njc2OTcyfQ.bOetMkDgNi7Mgd3Z1lq5Xqb30tD89cd3KMxScAY39jo'
> Draft: Feature/557578 session management

- src/stories/infrastructure/persistence/relational/mappers/story.mapper.ts
> fix: [BE-290362] miss story topic

- src/casl/ability.factory.ts
- src/hubers/hubers.controller.ts
- src/reading-sessions/reading-sessions.controller.ts
- src/stories/dto/find-all-stories.dto.ts
- src/stories/infrastructure/persistence/relational/repositories/story.repository.ts
- src/stories/infrastructure/persistence/story.repository.ts
- src/stories/stories.controller.ts
- src/stories/stories.service.ts
- src/topics/infrastructure/persistence/relational/entities/topics.entity.ts
Ticket url: https://c5qcgij075a.sg.larksuite.com/record/Irkur3AfYeyWJycZvY5lFVmfgBf
'http://localhost:3001/api/v1/stories?topicIds=10' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6eyJpZCI6MywibmFtZSI6IlJlYWRlciIsIl9fZW50aXR5IjoiUm9sZUVudGl0eSJ9LCJzZXNzaW9uSWQiOjIsImlhdCI6MTc0ODIyOTgxOSwiZXhwIjoxNzQ4MzE2MjE5fQ.o6qU2gqoFGieiXsuPe4ev2a_T2T6HusK7PAKsHlRgmY'
{
"data": [
{
"abstract": "Có những khoảnh khắc trong đời, ta giật mình nhận ra mình đã trôi qua bao nhiêu tháng ngày mà không thực sự \"sống\". Tôi từng như vậy. Một người luôn cố gắng để làm hài lòng người khác, để không làm ai thất vọng, để đạt được những tiêu chuẩn vô hình mà tôi chẳng bao giờ đặt câu hỏi liệu chúng có thực sự dành cho mình hay …
> fix(237661): fixed filtering stories by topics

- src/stories/infrastructure/persistence/relational/mappers/story.mapper.ts
Error when check log in PROD:
Tested in LOCAL:
> fix: pkey dup when create story

- src/reading-sessions/reading-sessions.service.ts
- src/web-rtc/web-rtc.module.ts
- src/web-rtc/web-rtc.service.ts
https://c5qcgij075a.sg.larksuite.com/record/T0T2rhF1kejrgqc3imKlyw5jgT9
> fix(522063): fixed generating Agora token

- prisma/migrations/20250611031941_remove_notification_story_relation/migration.sql
- prisma/schema.prisma
- src/database/seeds/relational/notification/notification-seed.service.ts
- src/notifications/notifications.controller.ts
- src/notifications/notifications.service.ts
> Update schema service notification

- src/stories/infrastructure/persistence/relational/repositories/story.repository.ts
> fix: fetch stories with cover url

- src/notifications/notifications.service.ts
'http://localhost:3001/api/v1/notifications?page=1&limit=10' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6eyJpZCI6MSwibmFtZSI6IkFkbWluIiwiX19lbnRpdHkiOiJSb2xlRW50aXR5In0sInNlc3Npb25JZCI6MjYsImlhdCI6MTc0OTc4NzM1NywiZXhwIjoxNzQ5ODczNzU3fQ.QSY7TooOmKv_dnO5qa0W8BwE-N_FWLV2ETTlvW54AAg'
> [168744] return session status and story review count in noti res

- src/auth/auth.service.ts
- src/users/users.controller.ts
- src/users/users.service.ts
> [958860 ] Fix inactive user cannot login

- src/fav-stories/fav-stories.service.ts
> [239792] update human book info fav stories

- src/users/dto/get-user-reading-sessions-query.dto.ts
- src/users/users.controller.ts
- src/users/users.service.ts
'http://localhost:3001/api/v1/users/1/reading-session?sessionStatus=approved' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwicm9sZSI6eyJpZCI6MSwibmFtZSI6IkFkbWluIiwiX19lbnRpdHkiOiJSb2xlRW50aXR5In0sInNlc3Npb25JZCI6NjgsImlhdCI6MTc1MDY4MzUzOSwiZXhwIjoxNzUwNzY5OTM5fQ.-xPImSScHoTLC4fOnr3T4P3wH4P-t-5I5Uts-ogLB1o'
> [552020] filter user's sessions by status

- src/hubers/hubers.controller.ts
- src/hubers/hubers.service.ts
- src/stories/stories.service.ts
'http://localhost:3001/api/v1/hubers/3/stories?page=1&limit=10' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6eyJpZCI6MiwibmFtZSI6Ikh1YmVyIiwiX19lbnRpdHkiOiJSb2xlRW50aXR5In0sInNlc3Npb25JZCI6NzcsImlhdCI6MTc1MDgzNzI1NCwiZXhwIjoxNzUwOTIzNjU0fQ.oG56nTycWU8SAXUpuplfsJcQxhzuapzgoxEQW2mkQSE'
> [539736] fetch huber's stories

- src/i18n/en/booking-email.json
- src/i18n/en/common.json
- src/i18n/vi/booking-email.json
- src/i18n/vi/common.json
- src/mail/mail-templates/booking.hbs
- src/mail/mail.service.ts
- src/reading-sessions/reading-sessions.processor.ts
- src/reading-sessions/reading-sessions.service.ts
> [476990] send mail when user booking session

- src/users/users.service.ts
> [522654] update human book topic get me response

- src/i18n/en/booking-email.json
- src/i18n/en/common.json
- src/i18n/en/reminder-email.json
- src/i18n/vi/booking-email.json
- src/i18n/vi/common.json
- src/i18n/vi/reminder-email.json
- src/mail/mail-templates/booking.hbs
- src/mail/mail-templates/reminder.hbs
- src/mail/mail.service.ts
- src/reading-sessions/reading-sessions.processor.ts
> [545904] modify reading session mail template

- src/stories/domain/story.ts
- src/stories/dto/create-story.dto.ts
- src/stories/infrastructure/persistence/relational/entities/story.entity.ts
- src/stories/infrastructure/persistence/relational/mappers/story.mapper.ts
- src/stories/stories.controller.ts
curl -X 'PATCH' \
'http://localhost:3001/api/v1/stories/5' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6eyJpZCI6MiwibmFtZSI6Ikh1YmVyIiwiX19lbnRpdHkiOiJSb2xlRW50aXR5In0sInNlc3Npb25JZCI6NCwiaWF0IjoxNzUyMzEwMjg0LCJleHAiOjE3NTIzOTY2ODR9.BN7GEPQuZbkA1Ktox8RVd9t06T7ZTP3BzW8erp-n-XA' \
-H 'Content-Type: application/json' \
-d '{
"rejectionReason": "qua do nha ba"
}'
> feat: update story with rejectReason on rejecting story

- src/search/search.service.ts
> Feat add highlight into search result

- prisma/migrations/20250731144730_add_report_model/migration.sql
- prisma/schema.prisma
- src/app.module.ts
- src/reports/domain/report.ts
- src/reports/dto/create-report.dto.ts
- src/reports/infrastructure/persistence/relational/entities/report.entity.ts
- src/reports/infrastructure/persistence/relational/mappers/report.mapper.ts
- src/reports/infrastructure/persistence/relational/relational-persistence.module.ts
- src/reports/infrastructure/persistence/relational/repositories/report.repository.ts
- src/reports/infrastructure/persistence/report.repository.ts
- src/reports/reports.controller.ts
- src/reports/reports.module.ts
- src/reports/reports.service.ts
curl -X 'POST' \
'http://localhost:3001/api/v1/reports' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6eyJpZCI6MywibmFtZSI6IkxpYmVyIiwiX19lbnRpdHkiOiJSb2xlRW50aXR5In0sInNlc3Npb25JZCI6MTAsImlhdCI6MTc1Mzk3NDQ0OSwiZXhwIjoxNzU0MDYwODQ5fQ.FgyUI4Li-Xw6nl4Ab2g0x4dPyYt_1AqSO1LDxyn46BU' \
-H 'Content-Type: application/json' \
-d '{
"reportedUserId": 5,
"reason": "khong hai"
}'
> feat(787260): create report huber api

- src/stories/stories.service.ts
> fix(603141): add countTopics rating in story detail res

- prisma/migrations/20250806132646_add_reject_reading_session_reason/migration.sql
- prisma/schema.prisma
- src/database/seeds/relational/notification-type/notification-type-seed.service.ts
- src/notifications/notification-type.enum.ts
- src/notifications/notifications.service.ts
- src/reading-sessions/reading-sessions.service.ts
> feat(943089): push notifs when huber approve/reject reading session

- src/database/seeds/relational/notification-type/notification-type-seed.service.ts
- src/notifications/notification-type.enum.ts
- src/notifications/notifications.service.ts
- src/reading-sessions/reading-sessions.service.ts
> feat(636985): push notifs when liber cancel reading session

- src/database/seeds/relational/notification-type/notification-type-seed.service.ts
- src/notifications/notification-type.enum.ts
- src/notifications/notifications.service.ts
- src/stories/status.enum.ts
- src/stories/stories.service.ts
> feat(655495): push notif when admin reject request publish story

- src/hubers/dto/report-huber.dto.ts
- src/hubers/hubers.controller.ts
- src/hubers/hubers.module.ts
- src/users/users.controller.ts
Ticket URL: https://c5qcgij075a.sg.larksuite.com/record/AdSxrXxVaeAJB9cFy9RlVVIsgob
> fix(588240): modify reporting huber API endpoint

- src/i18n/en/reminder-email.json
- src/i18n/vi/reminder-email.json
- src/notifications/notifications.service.ts
- src/reading-sessions/domain/reading-session.ts
- src/reading-sessions/dto/reading-session/update-reading-session.dto.ts
- src/reading-sessions/infrastructure/persistence/relational/entities/reading-session.entity.ts
- src/reading-sessions/infrastructure/persistence/relational/mappers/reading-sessions.mapper.ts
- src/reading-sessions/reading-sessions.controller.ts
- src/reading-sessions/reading-sessions.service.ts
- src/time-slots/time-slots.controller.ts
- src/web-rtc/web-rtc.service.ts
> fix: Hotfix session flow and notifs
